import NavHeader from "@/components/NavHeader";
import "@/styles/global.css";
import styles from "@/styles/EditorStyles.module.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <NavHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
